# Generated by Django 3.2.6 on 2021-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
